apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
spec:
  type: NodePort
  selector:
    app: demo-voting-app
    name: voting-app-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
